/**
 * Sample game specs + generated component source, keyed to the real Ramp
 * reports in `HARDCODED_GAMES`. Used by the Studio mock pipeline so the
 * science-fair demo streams believable, reliable output every time.
 *
 * These mirror the Phase-2 pipeline contract in PRD.md:
 *   excerpt → Claude spec (structured fields) → Cursor `GameComponent.tsx`.
 */

import { HARDCODED_GAMES } from "@/lib/games";

/** The structured fields Claude returns (PRD.md Phase 2, Step 1). */
export type SpecField =
  | "concept_name"
  | "mechanic"
  | "hook"
  | "closing_stat_template"
  | "difficulty_curve"
  | "ui_description";

export type GameSpec = Record<SpecField, string>;

/** Human labels + the agent that authors each field, for the Spec panel. */
export const SPEC_FIELDS: { id: SpecField; label: string; agent: string }[] = [
  { id: "concept_name", label: "concept_name", agent: "Claude" },
  { id: "hook", label: "hook", agent: "Claude" },
  { id: "closing_stat_template", label: "closing_stat_template", agent: "Claude" },
  { id: "mechanic", label: "mechanic", agent: "Claude" },
  { id: "difficulty_curve", label: "difficulty_curve", agent: "Claude" },
  { id: "ui_description", label: "ui_description", agent: "Claude" },
];

/** Which fields are authored during "Extract insight" vs "Design mechanic". */
export const INSIGHT_FIELDS: SpecField[] = [
  "concept_name",
  "hook",
  "closing_stat_template",
];
export const MECHANIC_FIELDS: SpecField[] = [
  "mechanic",
  "difficulty_curve",
  "ui_description",
];

export interface SampleSpec {
  /** Matches a `HARDCODED_GAMES` slug. */
  slug: string;
  report: string;
  excerpt: string;
  /** Simulated size of the scraped source doc, for believable status copy. */
  sourceWords: number;
  fileName: string;
  spec: GameSpec;
  /** The "Cursor-generated" component source, streamed line-by-line. */
  code: string;
}

const SPEND_SORT_CODE = `"use client";
import { useState, useEffect, useCallback } from "react";

type Tier = 0 | 1 | 2;
type Task = { id: number; label: string; tier: Tier; born: number };

const TIERS = ["Cheap / Fast", "Balanced", "Expensive"];
const FEED = ["OCR a receipt", "Draft a memo", "Reconcile ledger", "Classify txn"];

// Generated by Cursor from the Ramp "third pillar" funding announcement.
export default function SpendSort({ onComplete }: GameProps) {
  const [queue, setQueue] = useState<Task[]>([]);
  const [budget, setBudget] = useState(100);
  const [score, setScore] = useState(0);

  const spawn = useCallback(() => {
    const tier = Math.floor(Math.random() * 3) as Tier;
    setQueue((q) => [...q, { id: Date.now(), label: FEED[tier], tier, born: Date.now() }]);
  }, []);

  useEffect(() => {
    const rate = Math.max(400, 1200 - score * 20);
    const t = setInterval(spawn, rate);
    return () => clearInterval(t);
  }, [spawn, score]);

  const route = (task: Task, bucket: Tier) => {
    const correct = task.tier === bucket;
    setBudget((b) => b - (correct ? 2 : 6));
    setScore((s) => s + (correct ? 1 : 0));
    setQueue((q) => q.filter((t) => t.id !== task.id));
  };

  useEffect(() => {
    if (budget <= 0) {
      const saved = Math.round(60 + score * 0.4);
      onComplete({ score, stat: \`Saved \${saved}% vs. all-expensive routing\` });
    }
  }, [budget, score, onComplete]);

  return (
    <div className="grid gap-4 font-sans">
      <BudgetBar value={budget} score={score} />
      <TaskQueue tasks={queue} tiers={TIERS} onRoute={route} />
    </div>
  );
}
`;

const TRIAGE_CODE = `"use client";
import { useState, useEffect, useRef } from "react";

type Kind = "routine" | "judgment";
type Request = { id: number; vendor: string; amount: number; kind: Kind };

const VENDORS = ["Notion", "AWS", "Ramp Travel", "Figma", "Anthropic"];

// Generated by Cursor from the "AI agents for procurement" launch.
export default function Triage({ onComplete }: GameProps) {
  const [queue, setQueue] = useState<Request[]>([]);
  const [reviewed, setReviewed] = useState(0);
  const [autoHandled, setAutoHandled] = useState(0);
  const clock = useRef(30);

  useEffect(() => {
    const t = setInterval(() => {
      const kind: Kind = Math.random() > 0.55 ? "routine" : "judgment";
      setQueue((q) => [...q, {
        id: Date.now(),
        vendor: VENDORS[Math.floor(Math.random() * VENDORS.length)],
        amount: Math.round(Math.random() * 4000),
        kind,
      }]);
    }, 900);
    return () => clearInterval(t);
  }, []);

  // The agent clears routine requests so the human only sees judgment calls.
  useEffect(() => {
    const auto = setInterval(() => {
      setQueue((q) => {
        const routine = q.filter((r) => r.kind === "routine");
        if (routine.length) setAutoHandled((n) => n + 1);
        return q.filter((r) => r.kind !== "routine");
      });
    }, 2000);
    return () => clearInterval(auto);
  }, []);

  const decide = (id: number) => {
    setReviewed((n) => n + 1);
    setQueue((q) => q.filter((r) => r.id !== id));
  };

  return <TriageBoard queue={queue} onDecide={decide} clock={clock.current} />;
}
`;

const THEN_VS_NOW_CODE = `"use client";
import { useState, useRef } from "react";

type Round = "manual" | "auto";
type Receipt = { id: number; merchant: string; category: string };

const RECEIPTS: Receipt[] = seedReceipts(8);

// Generated by Cursor from the original receipt-automation product page.
export default function ThenVsNow({ onComplete }: GameProps) {
  const [round, setRound] = useState<Round>("manual");
  const [index, setIndex] = useState(0);
  const start = useRef(performance.now());
  const manualMs = useRef(0);

  const submit = (typed: string) => {
    const r = RECEIPTS[index];
    const ok = round === "auto" || typed.trim() === r.category;
    if (!ok) return;
    if (index + 1 < RECEIPTS.length) {
      setIndex((i) => i + 1);
      return;
    }
    const elapsed = performance.now() - start.current;
    if (round === "manual") {
      manualMs.current = elapsed;
      setRound("auto");
      setIndex(0);
      start.current = performance.now();
    } else {
      const m = Math.floor(manualMs.current / 60000);
      const s = Math.round((manualMs.current % 60000) / 1000);
      onComplete({
        score: Math.round(manualMs.current / elapsed),
        stat: \`Manual: \${m}m \${s}s · Automated: \${(elapsed / 1000).toFixed(1)}s\`,
      });
    }
  };

  return <RaceBoard round={round} receipt={RECEIPTS[index]} onSubmit={submit} />;
}
`;

const bySlug = (slug: string) => HARDCODED_GAMES.find((g) => g.slug === slug)!;

export const SAMPLE_SPECS: SampleSpec[] = [
  {
    slug: "spend-sort",
    report: bySlug("spend-sort").source.report,
    excerpt: bySlug("spend-sort").source.excerpt,
    sourceWords: 1240,
    fileName: "SpendSort.tsx",
    spec: {
      concept_name: "Spend Sort",
      hook: "Every task you misroute to the expensive model quietly drains the budget bar.",
      closing_stat_template: "You saved {X}% vs. routing everything to the expensive tier.",
      mechanic:
        "Resource-sorting under pressure. Tasks pile into a queue that spawns faster over time; drag each into one of three model-cost buckets (Cheap/Fast, Balanced, Expensive). A wrong bucket bounces the task back and burns double the budget.",
      difficulty_curve:
        "Spawn interval decays from 1200ms → 400ms as score climbs; budget also drains passively so hesitation costs money.",
      ui_description:
        "Left: draining budget bar in solar. Center: falling task cards. Bottom: three labeled drop buckets with hairline borders. Light canvas, mono labels, no shadows.",
    },
    code: SPEND_SORT_CODE,
  },
  {
    slug: "triage",
    report: bySlug("triage").source.report,
    excerpt: bySlug("triage").source.excerpt,
    sourceWords: 980,
    fileName: "Triage.tsx",
    spec: {
      concept_name: "Triage",
      hook: "The agent quietly clears the routine requests — you only ever touch the hard calls.",
      closing_stat_template:
        "You reviewed {N} requests; the agent handled {M} — ~{Z} hours saved.",
      mechanic:
        "Judgment under volume. Request cards stream in and must be approved, flagged, or escalated. Routine requests auto-resolve after 2s (the agent handles them); judgment calls demand a decision within 3s or they're missed.",
      difficulty_curve:
        "Inflow starts at 900ms and tightens; the ratio of judgment-to-routine cards rises so the human load compounds.",
      ui_description:
        "A dense board of request cards with vendor + amount in mono. Approve/flag/escalate as three keyboard-first actions. Agent-cleared cards fade to a muted 'handled' lane.",
    },
    code: TRIAGE_CODE,
  },
  {
    slug: "then-vs-now",
    report: bySlug("then-vs-now").source.report,
    excerpt: bySlug("then-vs-now").source.excerpt,
    sourceWords: 760,
    fileName: "ThenVsNow.tsx",
    spec: {
      concept_name: "Then vs. Now",
      hook: "Round one you type every field by hand. Round two, one click — feel the delta.",
      closing_stat_template: "Manual: {X}m {Y}s · Automated: {Z}s.",
      mechanic:
        "Head-to-head timed race. Round 1: manual receipt entry — type the merchant, hunt for the category, confirm. Round 2: the same receipts, automated — one click, pre-filled. The timer delta is the whole point.",
      difficulty_curve:
        "Manual round adds friction (category picker, validation); automated round removes it entirely so the gap is visceral, not incremental.",
      ui_description:
        "Split race track: a 'Then' lane and a 'Now' lane. Live stopwatch in mono, solar progress fill. Final screen stacks the two times for a screenshot-ready comparison.",
    },
    code: THEN_VS_NOW_CODE,
  },
];

/** Match a pasted excerpt / URL to the best sample; falls back to the first. */
export function findSampleForInput(input: string): SampleSpec {
  const text = input.trim().toLowerCase();
  if (!text) return SAMPLE_SPECS[0];
  const scored = SAMPLE_SPECS.map((s) => {
    const haystack = `${s.report} ${s.excerpt} ${s.slug}`.toLowerCase();
    let score = 0;
    if (haystack.includes(text) || text.includes(s.excerpt.toLowerCase())) score += 100;
    for (const word of text.split(/\s+/)) {
      if (word.length > 3 && haystack.includes(word)) score += 1;
    }
    return { s, score };
  });
  scored.sort((a, b) => b.score - a.score);
  return scored[0].score > 0 ? scored[0].s : SAMPLE_SPECS[0];
}
